apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-server
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
  annotations:
    {{- include "unikorn.ingress.clusterIssuer.annotations" . | nindent 4 }}
    {{- include "unikorn.ingress.mtls.annotations" . | nindent 4 }}
    {{- if (include "unikorn.ingress.externalDNS" .) }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "unikorn.region.host" . }}
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
spec:
  {{- if .Values.ingress.class }}
  ingressClassName: {{ .Values.ingress.class }}
  {{- end }}
  # For development you will want to add these names to /etc/hosts for the ingress
  # endpoint address.
  tls:
  - hosts:
    - {{ include "unikorn.region.host" . }}
    secretName: {{ .Release.Name }}-ingress-tls
  rules:
  # The the UI is written as a JAMstack application, so the API is accessed via
  # the same host to avoid CORS, and therefore uses routing to hit the correct
  # service.
  - host: {{ include "unikorn.region.host" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-server
            port:
              name: http
