apiVersion: v2
name: unikorn-region
description: A Helm chart for deploying Unikorn's Region Controller

type: application

version: 1.14.2
appVersion: 1.14.2

icon: https://raw.githubusercontent.com/unikorn-cloud/assets/main/images/logos/dark-on-light/icon.png

dependencies:
- name: unikorn-common
  version: 0.1.16
  repository: https://nscaledev.github.io/uni-helm-common
