apiVersion: v2
name: unikorn-region
description: A Helm chart for deploying Unikorn's Region Controller

type: application

version: v0.1.46
appVersion: v0.1.46

icon: https://raw.githubusercontent.com/unikorn-cloud/assets/main/images/logos/dark-on-light/icon.png

dependencies:
- name: unikorn-common
  version: v0.1.13
  repository: https://unikorn-cloud.github.io/helm-common
