apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: network-resources.compute.unikorn-cloud.org
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - region.unikorn-cloud.org
      apiVersions:
      - '*'
      resources:
      - networks
      operations:
      - CREATE
      - UPDATE
  validations:
  - expression: "object.metadata.?labels[?'unikorn-cloud.org/name'].orValue('') != ''"
    message: Resource must contain a unikorn-cloud.org/name label
  - expression: "object.metadata.?labels[?'unikorn-cloud.org/organization'].orValue('') != ''"
    message: Resource must contain a unikorn-cloud.org/organization label
  - expression: "oldObject == null || oldObject.metadata.?labels[?'principal.unikorn-cloud.org/organization'].orValue('') ==  object.metadata.?labels[?'principal.unikorn-cloud.org/organization'].orValue('')"
    message: Resource principal/unikorn-cloud.org/organization label is immutable
  - expression: "object.metadata.?labels[?'unikorn-cloud.org/project'].orValue('') != ''"
    message: Resource must contain a unikorn-cloud.org/project label
  - expression: "oldObject == null || oldObject.metadata.?labels[?'principal.unikorn-cloud.org/project'].orValue('') ==  object.metadata.?labels[?'principal.unikorn-cloud.org/project'].orValue('')"
    message: Resource principal/unikorn-cloud.org/project label is immutable
  - expression: "object.metadata.?labels[?'regions.unikorn-cloud.org/identity-id'].orValue('') != ''"
    message: Resource must contain a regions.unikorn-cloud.org/identity-id label
  - expression: "object.metadata.?labels[?'regions.unikorn-cloud.org/region-id'].orValue('') != ''"
    message: Resource must contain a regions.unikorn-cloud.org/region-id label
  - expression: "object.metadata.?annotations[?'unikorn-cloud.org/allocation-id'].orValue('') != ''"
    message: Resource must contain a unikorn-cloud.org/allocation-id annotation
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: network-resources.compute.unikorn-cloud.org
spec:
  policyName: network-resources.compute.unikorn-cloud.org
  validationActions:
  - Deny
