---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.3
  name: filestorages.region.unikorn-cloud.org
spec:
  group: region.unikorn-cloud.org
  names:
    categories:
    - unikorn
    kind: FileStorage
    listKind: FileStorageList
    plural: filestorages
    singular: filestorage
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=="Available")].reason
      name: status
      type: string
    - jsonPath: .spec.size
      name: size
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: FileStorage defines a FileStorageSpec.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: FileStorageSpec defines the storage request.
            properties:
              attachments:
                description: Attachments are the network attachments for the storage.
                items:
                  description: Attachment has the network identifier for the storage.
                  properties:
                    ipRange:
                      description: IPRange is the IP range for the attachment.
                      properties:
                        endIP:
                          description: End is the end IP address for the attachment.
                          pattern: ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])$
                          type: string
                        startIP:
                          description: Start is the start IP address for the attachment.
                          pattern: ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])$
                          type: string
                      required:
                      - endIP
                      - startIP
                      type: object
                    networkID:
                      description: NetworkID is the network ID for the attachment.
                      type: string
                    segmentationID:
                      description: SegmentationID is the VLAN ID for the attachment.
                      maximum: 4094
                      minimum: 1
                      type: integer
                  required:
                  - networkID
                  type: object
                type: array
              nfs:
                description: NFS is fulfilled when leveraging the NFS storage class.
                properties:
                  rootSquash:
                    type: boolean
                type: object
              pause:
                description: Pause, if true, will inhibit reconciliation.
                type: boolean
              size:
                anyOf:
                - type: integer
                - type: string
                description: Size is the total size of the file storage.
                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                x-kubernetes-int-or-string: true
              storageClassID:
                description: StorageClassID is the storage class ID.
                type: string
              tags:
                description: |-
                  Tags are an abitrary list of key/value pairs that a client
                  may populate to store metadata for the resource.
                  Tags are aribrary user data.
                items:
                  description: Tag is an arbirary key/value.
                  properties:
                    name:
                      description: Name of the tag.
                      type: string
                    value:
                      description: Value of the tag.
                      type: string
                  required:
                  - name
                  - value
                  type: object
                type: array
            required:
            - size
            - storageClassID
            type: object
          status:
            properties:
              attachments:
                description: Attachments reflects the observed attachment state per
                  network.
                items:
                  properties:
                    message:
                      description: Human-readable message indicating details about
                        the attachment.
                      type: string
                    networkID:
                      description: NetworkID is the network ID for the attachment.
                      type: string
                    provisioningStatus:
                      description: ProvisioningStatus indicates if this attachment
                        is ready/failed/etc.
                      enum:
                      - Provisioning
                      - Provisioned
                      - Errored
                      - Deprovisioning
                      type: string
                    segmentationID:
                      description: SegmentationID is the VLAN ID for the attachment.
                      type: integer
                  required:
                  - message
                  - networkID
                  - provisioningStatus
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - networkID
                x-kubernetes-list-type: map
              conditions:
                description: Current service state of a file storage.
                items:
                  description: |-
                    Condition is a generic condition type for use across all resource types.
                    It's generic so that the underlying controller-manager functionality can
                    be shared across all resources.
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the condition's
                        last transition.
                      enum:
                      - Provisioning
                      - Provisioned
                      - Cancelled
                      - Errored
                      - Deprovisioning
                      - Deprovisioned
                      - Unknown
                      - Healthy
                      - Degraded
                      type: string
                    status:
                      description: |-
                        Status is the status of the condition.
                        Can be True, False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the condition.
                      enum:
                      - Available
                      - Healthy
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              mountPath:
                description: MountPath is the path where the file storage is mounted.
                type: string
              observedGeneration:
                description: ObservedGeneration is the most recent generation observed
                  by the controller.
                format: int64
                type: integer
              size:
                anyOf:
                - type: integer
                - type: string
                description: |-
                  Size is the currently provisioned/observed size of the file storage.
                  (May differ from spec.size while provisioning/resizing.)
                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                x-kubernetes-int-or-string: true
              usage:
                anyOf:
                - type: integer
                - type: string
                description: Usage is the amount of storage currently in use.
                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                x-kubernetes-int-or-string: true
              usageTimestamp:
                description: UsageTimestamp is the timestamp when the usage was last
                  updated.
                format: date-time
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
